# Generated by Django 4.1.5 on 2023-01-11 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feteamapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='UnitClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('academyImage', models.ImageField(upload_to='images')),
                ('warImage', models.ImageField(upload_to='images')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('house', models.CharField(max_length=50, verbose_name='House')),
                ('defaultClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feteamapp.unitclass')),
                ('personalAbility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feteamapp.ability')),
            ],
        ),
    ]
