# Generated by Django 4.1.5 on 2023-01-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feteamapp', '0002_ability_unitclass_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitclass',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='unitclass',
            name='genderLocked',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=50, verbose_name='Genderlocked'),
        ),
        migrations.AddField(
            model_name='unitclass',
            name='level',
            field=models.CharField(blank=True, choices=[('base', 'Base'), ('unique', 'Unique'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('dlc', 'DLC'), ('master', 'Master')], max_length=50, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='unitclass',
            name='sprite',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='academyImage',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='house',
            field=models.CharField(blank=True, choices=[('eagles', 'Black Eagles'), ('lions', 'Blue Lions'), ('deer', 'Golden Deer'), ('wolves', 'Ashen Wolves'), ('church', 'Church of Seiros')], max_length=50, verbose_name='House'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='warImage',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
