# Generated by Django 4.1.5 on 2023-01-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feteamapp', '0011_alter_unit_exclusiveabilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitclass',
            name='uniqueTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feteamapp.unit'),
        ),
    ]
