# Generated by Django 4.1.5 on 2023-01-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feteamapp', '0014_remove_unitclass_proficiencies_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiency',
            name='type',
            field=models.CharField(choices=[('gen', 'General'), ('char', 'Character Ability'), ('classab', 'Class Mastery'), ('class', 'Class Requierment')], max_length=20),
        ),
    ]
