# Generated by Django 4.1.5 on 2023-01-13 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feteamapp', '0015_alter_proficiency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proficiency',
            name='abex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feteamapp.ability'),
        ),
    ]
