# Generated by Django 4.1.5 on 2023-01-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feteamapp', '0016_proficiency_abex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='exclusiveAbilities',
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='level',
            field=models.CharField(blank=True, choices=[('e', 'E'), ('e+', 'E+'), ('d', 'D'), ('d+', 'D+'), ('c,', 'C'), ('c+', 'C+'), ('b', 'B'), ('b+', 'B+'), ('a', 'A'), ('a+', 'A+'), ('s', 'S'), ('s+', 'S+'), ('mastery', 'Mastery'), ('bud', 'Budding Talent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='prof',
            field=models.CharField(blank=True, choices=[('sword', 'Sword'), ('lance', 'Lance'), ('axe', 'Axe'), ('bow', 'Bow'), ('brawl', 'Brawl'), ('reason', 'Reason'), ('faith', 'Faith'), ('authority', 'Authority'), ('riding', 'Riding'), ('flying', 'Flying'), ('armor', 'Armor')], max_length=20, null=True),
        ),
    ]
